name: Java CI with Gradle

on:
  push:
    branches: [ "1.20" ]
  pull_request:
    branches: [ "1.20" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permission for Gradle Wrapper
      run: chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build
